@InterviewAPI_HostAddress = http://localhost:5287


### Login Request
POST {{InterviewAPI_HostAddress}}/api/authentication/login
Content-Type: application/json

{
  "username": "Seth",
  "password": "amplifund"
}

### Get All Cameras (Requires JWT Token)
GET {{InterviewAPI_HostAddress}}/api/cameras
Authorization: Bearer 
Accept: application/json
